name: saas_web_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  google_fonts: 
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.2+1
  permission_handler: ^8.1.4+2  
  socket_io_client: "0.9.12"
  fluttertoast:
  flutter_animarker: ^3.2.0
  maps_curved_line: ^1.0.2
  puppeteer: 
  flutter_spinkit: 
  
  # url_launcher: 

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

get_cli:
  sub_folder: false

flutter: 

  assets:
    - assets/maps/
    
  uses-material-design: true

